import type {
  AdminDataBatchCommand,
  CreateVisitorSessionCommand,
  PublishAdminDataCommand,
  VisitorSessionBatchCommand,
} from "../domain/types.js";

/** Identity already verified by a trusted server-side authentication adapter. */
export interface VerifiedIdentity {
  readonly subjectId: string;
  readonly provider: string;
  readonly authenticatedAt: string;
  readonly expiresAt: string;
  readonly email?: string;
}

export type CompanyRole = "admin";

/** Server-side company authorization record. Roles are never accepted from UI input. */
export interface CompanyAccessGrant {
  readonly companyId: string;
  readonly subjectId: string;
  readonly role: CompanyRole;
  readonly active: boolean;
  readonly grantedAt: string;
  readonly grantedBy: string;
  readonly revokedAt?: string;
  readonly revokedBy?: string;
}

export type AuthorizedAdminDataBatchCommand = Omit<
  AdminDataBatchCommand,
  "actorId" | "occurredAt"
>;

export type AuthorizedPublishAdminDataCommand = Omit<
  PublishAdminDataCommand,
  "publishedBy" | "publishedAt"
>;

/** Session id and access token are generated by the server, never chosen by UI input. */
/** Trusted server-side command after server time and TTL have been applied. */
export type ProtectedCreateVisitorSessionCommand = Omit<
  CreateVisitorSessionCommand,
  "sessionId"
>;

/** Browser-safe visitor request. Dates and the session id are server-generated. */
export type ProtectedCreateVisitorSessionRequest = Pick<
  CreateVisitorSessionCommand,
  "companyId" | "publicationVersion" | "horizon"
>;

export interface VisitorSessionCredential {
  readonly sessionId: string;
  readonly accessToken: string;
}

export interface ProtectedVisitorSessionHandle<View> {
  readonly credential: VisitorSessionCredential;
  readonly view: View;
}

export type ProtectedVisitorSessionBatchCommand = Omit<
  VisitorSessionBatchCommand,
  "sessionId" | "occurredAt"
> & VisitorSessionCredential;

export interface ProtectedResetVisitorSessionCommand
extends VisitorSessionCredential {
  readonly expectedRevision: number;
}

export interface VisitorSessionAccessRecord {
  readonly sessionId: string;
  readonly tokenHash: string;
  readonly createdAt: string;
  readonly expiresAt: string;
  readonly revokedAt?: string;
}
